id: P008210
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1KG12063
  title: རྒྱུད་བླ་མའི་འགྲེལ་པ་ངེས་དོན་གསལ་བར་བྱེད་པའི་འོད་ཟེར།
  author: ''
  volumes:
    282a20289241459987f651e855f11c5e:
      image_group_id: I1KG12067
      title: ''
      volume_number: 1
      total_pages: 208
      base_file: v001.txt
